io:
  input:  { kind: json_dir, path: ./data/branches_minimal }
  output: { kind: json_dir, path: ./tmp/report }
pipeline:
  - step: plugin
    func: plugins.extractions.branch_manager_summary.extract_branch_manager_summary
