# pipelines/demo_fk_helpers.yaml
io:
  input:  { kind: json_dir, path: ./data/branches_minimal }
  output: { kind: xlsx,     path: ./tmp/branches_with_helpers.xlsx }

pipeline:
  - step: validate
    defaults:
      id_field: id
      label_field: name
      detect_fk: true
      helper_prefix: "_"

  - step: apply_fks
    defaults:
      id_field: id
      label_field: name
      detect_fk: true
      helper_prefix: "_"

  - step: flatten_headers
    mode: level0

  - step: reorder_helpers

